<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="HotChocolate" Version="15.0.3" />
		<PackageReference Include="HotChocolate.Data" Version="15.0.3" />
		<PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.0.3" />
		<PackageReference Include="HotChocolate.Server" Version="10.5.5" />
		<PackageReference Include="HotChocolate.Utilities.DependencyInjection" Version="15.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
		<PackageReference Include="SqlDbMigrator" Version="1.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
		<PackageReference Include="HotChocolate.AspNetCore" Version="15.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TransactionalOutbox.Core\TransactionalOutbox.Core.csproj" />
		<ProjectReference Include="..\TransactionalOutbox.Infrastructure\TransactionalOutbox.Infrastructure.csproj" />
		<ProjectReference Include="..\TransactionalOutbox.Public\TransactionalOutbox.Public.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Migrations\*.sql">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Remove="Migrations\000_000_000_003_AddAddressTable.sql" />
	</ItemGroup>

</Project>
